import type { AchievementDefinition } from '@/types/achievement';

/**
 * Complete catalogue of achievements for OpenJapanese.
 *
 * Each entry matches the `AchievementDefinition` interface with a unique `key`,
 * human-readable `name`, `description`, badge `icon` path, `category`, a
 * machine-evaluable `condition`, `xpReward`, and `rarity`.
 *
 * Total: 61 achievements across 6 categories.
 */
export const ACHIEVEMENTS: AchievementDefinition[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // LEARNING (11)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: 'first_lesson',
    name: 'First Steps',
    description: 'Complete your first lesson',
    icon: '/images/badges/first_lesson.svg',
    category: 'learning',
    condition: { type: 'items_learned', count: 1 },
    xpReward: 50,
    rarity: 'common',
  },
  {
    key: 'lessons_10',
    name: 'Dedicated Student',
    description: 'Complete 10 lessons',
    icon: '/images/badges/lessons_10.svg',
    category: 'learning',
    condition: { type: 'items_learned', count: 10 },
    xpReward: 100,
    rarity: 'uncommon',
  },
  {
    key: 'lessons_50',
    name: 'Scholar',
    description: 'Complete 50 lessons',
    icon: '/images/badges/lessons_50.svg',
    category: 'learning',
    condition: { type: 'items_learned', count: 50 },
    xpReward: 300,
    rarity: 'rare',
  },
  {
    key: 'kanji_10',
    name: 'Kanji Beginner',
    description: 'Learn 10 kanji',
    icon: '/images/badges/kanji_10.svg',
    category: 'learning',
    condition: { type: 'kanji_count', count: 10 },
    xpReward: 50,
    rarity: 'common',
  },
  {
    key: 'kanji_50',
    name: 'Kanji Explorer',
    description: 'Learn 50 kanji',
    icon: '/images/badges/kanji_50.svg',
    category: 'learning',
    condition: { type: 'kanji_count', count: 50 },
    xpReward: 150,
    rarity: 'uncommon',
  },
  {
    key: 'kanji_100',
    name: 'Kanji Century',
    description: 'Learn 100 kanji',
    icon: '/images/badges/kanji_100.svg',
    category: 'learning',
    condition: { type: 'kanji_count', count: 100 },
    xpReward: 300,
    rarity: 'rare',
  },
  {
    key: 'kanji_500',
    name: 'Kanji Master',
    description: 'Learn 500 kanji',
    icon: '/images/badges/kanji_500.svg',
    category: 'learning',
    condition: { type: 'kanji_count', count: 500 },
    xpReward: 1000,
    rarity: 'epic',
  },
  {
    key: 'kanji_1000',
    name: 'Kanji Legend',
    description: 'Learn 1000 kanji',
    icon: '/images/badges/kanji_1000.svg',
    category: 'learning',
    condition: { type: 'kanji_count', count: 1000 },
    xpReward: 5000,
    rarity: 'legendary',
  },
  {
    key: 'vocab_100',
    name: 'Word Collector',
    description: 'Learn 100 vocabulary words',
    icon: '/images/badges/vocab_100.svg',
    category: 'learning',
    condition: { type: 'vocab_count', count: 100 },
    xpReward: 200,
    rarity: 'uncommon',
  },
  {
    key: 'vocab_500',
    name: 'Wordsmith',
    description: 'Learn 500 vocabulary words',
    icon: '/images/badges/vocab_500.svg',
    category: 'learning',
    condition: { type: 'vocab_count', count: 500 },
    xpReward: 500,
    rarity: 'rare',
  },
  {
    key: 'vocab_1000',
    name: 'Lexicon',
    description: 'Learn 1000 vocabulary words',
    icon: '/images/badges/vocab_1000.svg',
    category: 'learning',
    condition: { type: 'vocab_count', count: 1000 },
    xpReward: 1500,
    rarity: 'epic',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STREAK (8)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: 'streak_3',
    name: 'Getting Started',
    description: '3-day streak',
    icon: '/images/badges/streak_3.svg',
    category: 'streak',
    condition: { type: 'streak_days', count: 3 },
    xpReward: 30,
    rarity: 'common',
  },
  {
    key: 'streak_7',
    name: 'Week Warrior',
    description: '7-day streak',
    icon: '/images/badges/streak_7.svg',
    category: 'streak',
    condition: { type: 'streak_days', count: 7 },
    xpReward: 100,
    rarity: 'common',
  },
  {
    key: 'streak_14',
    name: 'Two Week Champion',
    description: '14-day streak',
    icon: '/images/badges/streak_14.svg',
    category: 'streak',
    condition: { type: 'streak_days', count: 14 },
    xpReward: 200,
    rarity: 'uncommon',
  },
  {
    key: 'streak_30',
    name: 'Monthly Master',
    description: '30-day streak',
    icon: '/images/badges/streak_30.svg',
    category: 'streak',
    condition: { type: 'streak_days', count: 30 },
    xpReward: 500,
    rarity: 'rare',
  },
  {
    key: 'streak_60',
    name: 'Unstoppable',
    description: '60-day streak',
    icon: '/images/badges/streak_60.svg',
    category: 'streak',
    condition: { type: 'streak_days', count: 60 },
    xpReward: 800,
    rarity: 'rare',
  },
  {
    key: 'streak_100',
    name: 'Century Streak',
    description: '100-day streak',
    icon: '/images/badges/streak_100.svg',
    category: 'streak',
    condition: { type: 'streak_days', count: 100 },
    xpReward: 1500,
    rarity: 'epic',
  },
  {
    key: 'streak_200',
    name: 'Dedicated Learner',
    description: '200-day streak',
    icon: '/images/badges/streak_200.svg',
    category: 'streak',
    condition: { type: 'streak_days', count: 200 },
    xpReward: 3000,
    rarity: 'epic',
  },
  {
    key: 'streak_365',
    name: 'Year of Dedication',
    description: '365-day streak',
    icon: '/images/badges/streak_365.svg',
    category: 'streak',
    condition: { type: 'streak_days', count: 365 },
    xpReward: 5000,
    rarity: 'legendary',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MASTERY (13)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: 'first_burn',
    name: 'Eternal Flame',
    description: 'Burn your first item',
    icon: '/images/badges/first_burn.svg',
    category: 'mastery',
    condition: { type: 'items_burned', count: 1 },
    xpReward: 100,
    rarity: 'common',
  },
  {
    key: 'burns_10',
    name: 'Memory Keeper',
    description: 'Burn 10 items',
    icon: '/images/badges/burns_10.svg',
    category: 'mastery',
    condition: { type: 'items_burned', count: 10 },
    xpReward: 200,
    rarity: 'uncommon',
  },
  {
    key: 'burns_50',
    name: 'Iron Memory',
    description: 'Burn 50 items',
    icon: '/images/badges/burns_50.svg',
    category: 'mastery',
    condition: { type: 'items_burned', count: 50 },
    xpReward: 500,
    rarity: 'rare',
  },
  {
    key: 'burns_100',
    name: 'Steel Mind',
    description: 'Burn 100 items',
    icon: '/images/badges/burns_100.svg',
    category: 'mastery',
    condition: { type: 'items_burned', count: 100 },
    xpReward: 1000,
    rarity: 'epic',
  },
  {
    key: 'burns_500',
    name: 'Enlightened One',
    description: 'Burn 500 items',
    icon: '/images/badges/burns_500.svg',
    category: 'mastery',
    condition: { type: 'items_burned', count: 500 },
    xpReward: 3000,
    rarity: 'legendary',
  },
  {
    key: 'jlpt_n5',
    name: 'N5 Complete',
    description: 'Master all JLPT N5 content',
    icon: '/images/badges/jlpt_n5.svg',
    category: 'mastery',
    condition: { type: 'jlpt_level', level: 'N5' },
    xpReward: 1000,
    rarity: 'rare',
  },
  {
    key: 'jlpt_n4',
    name: 'N4 Complete',
    description: 'Master all JLPT N4 content',
    icon: '/images/badges/jlpt_n4.svg',
    category: 'mastery',
    condition: { type: 'jlpt_level', level: 'N4' },
    xpReward: 2000,
    rarity: 'epic',
  },
  {
    key: 'jlpt_n3',
    name: 'N3 Complete',
    description: 'Master all JLPT N3 content',
    icon: '/images/badges/jlpt_n3.svg',
    category: 'mastery',
    condition: { type: 'jlpt_level', level: 'N3' },
    xpReward: 3000,
    rarity: 'epic',
  },
  {
    key: 'jlpt_n2',
    name: 'N2 Complete',
    description: 'Master all JLPT N2 content',
    icon: '/images/badges/jlpt_n2.svg',
    category: 'mastery',
    condition: { type: 'jlpt_level', level: 'N2' },
    xpReward: 5000,
    rarity: 'legendary',
  },
  {
    key: 'jlpt_n1',
    name: 'N1 Complete',
    description: 'Master all JLPT N1 content',
    icon: '/images/badges/jlpt_n1.svg',
    category: 'mastery',
    condition: { type: 'jlpt_level', level: 'N1' },
    xpReward: 10000,
    rarity: 'legendary',
  },
  {
    key: 'level_10',
    name: 'Double Digits',
    description: 'Reach level 10',
    icon: '/images/badges/level_10.svg',
    category: 'mastery',
    condition: { type: 'app_level', level: 10 },
    xpReward: 200,
    rarity: 'uncommon',
  },
  {
    key: 'level_30',
    name: 'Halfway There',
    description: 'Reach level 30',
    icon: '/images/badges/level_30.svg',
    category: 'mastery',
    condition: { type: 'app_level', level: 30 },
    xpReward: 1000,
    rarity: 'rare',
  },
  {
    key: 'level_60',
    name: 'Maximum Level',
    description: 'Reach level 60',
    icon: '/images/badges/level_60.svg',
    category: 'mastery',
    condition: { type: 'app_level', level: 60 },
    xpReward: 10000,
    rarity: 'legendary',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // REVIEWS (8)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: 'reviews_100',
    name: 'Reviewer',
    description: 'Complete 100 reviews',
    icon: '/images/badges/reviews_100.svg',
    category: 'learning',
    condition: { type: 'reviews_completed', count: 100 },
    xpReward: 50,
    rarity: 'common',
  },
  {
    key: 'reviews_500',
    name: 'Diligent',
    description: 'Complete 500 reviews',
    icon: '/images/badges/reviews_500.svg',
    category: 'learning',
    condition: { type: 'reviews_completed', count: 500 },
    xpReward: 200,
    rarity: 'uncommon',
  },
  {
    key: 'reviews_1000',
    name: 'Thousand Reviews',
    description: 'Complete 1000 reviews',
    icon: '/images/badges/reviews_1000.svg',
    category: 'learning',
    condition: { type: 'reviews_completed', count: 1000 },
    xpReward: 500,
    rarity: 'rare',
  },
  {
    key: 'reviews_5000',
    name: 'Review Machine',
    description: 'Complete 5000 reviews',
    icon: '/images/badges/reviews_5000.svg',
    category: 'learning',
    condition: { type: 'reviews_completed', count: 5000 },
    xpReward: 1500,
    rarity: 'epic',
  },
  {
    key: 'perfect_10',
    name: 'Perfect Ten',
    description: '10 correct reviews in a row',
    icon: '/images/badges/perfect_10.svg',
    category: 'learning',
    condition: { type: 'perfect_reviews', count: 10 },
    xpReward: 100,
    rarity: 'uncommon',
  },
  {
    key: 'perfect_25',
    name: 'Quarter Century',
    description: '25 correct reviews in a row',
    icon: '/images/badges/perfect_25.svg',
    category: 'learning',
    condition: { type: 'perfect_reviews', count: 25 },
    xpReward: 300,
    rarity: 'rare',
  },
  {
    key: 'perfect_50',
    name: 'Flawless Fifty',
    description: '50 correct reviews in a row',
    icon: '/images/badges/perfect_50.svg',
    category: 'learning',
    condition: { type: 'perfect_reviews', count: 50 },
    xpReward: 800,
    rarity: 'epic',
  },
  {
    key: 'speed_demon',
    name: 'Speed Demon',
    description: 'Complete 20 reviews in under 60 seconds',
    icon: '/images/badges/speed_demon.svg',
    category: 'learning',
    condition: { type: 'speed_review', itemCount: 20, maxSeconds: 60 },
    xpReward: 300,
    rarity: 'rare',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GAMES (8)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: 'first_game',
    name: 'Player One',
    description: 'Play your first mini-game',
    icon: '/images/badges/first_game.svg',
    category: 'games',
    condition: { type: 'games_played', count: 1 },
    xpReward: 30,
    rarity: 'common',
  },
  {
    key: 'games_10',
    name: 'Gamer',
    description: 'Play 10 mini-games',
    icon: '/images/badges/games_10.svg',
    category: 'games',
    condition: { type: 'games_played', count: 10 },
    xpReward: 100,
    rarity: 'common',
  },
  {
    key: 'games_50',
    name: 'Game Master',
    description: 'Play 50 mini-games',
    icon: '/images/badges/games_50.svg',
    category: 'games',
    condition: { type: 'games_played', count: 50 },
    xpReward: 300,
    rarity: 'uncommon',
  },
  {
    key: 'perfect_match',
    name: 'Perfect Match',
    description: 'Perfect score in matching game',
    icon: '/images/badges/perfect_match.svg',
    category: 'games',
    condition: { type: 'game_perfect', gameType: 'matching' },
    xpReward: 100,
    rarity: 'uncommon',
  },
  {
    key: 'speed_king',
    name: 'Speed King',
    description: 'Perfect score in speed round',
    icon: '/images/badges/speed_king.svg',
    category: 'games',
    condition: { type: 'game_perfect', gameType: 'speed-round' },
    xpReward: 200,
    rarity: 'rare',
  },
  {
    key: 'artist',
    name: 'Kanji Artist',
    description: 'Perfect score in kanji drawing',
    icon: '/images/badges/artist.svg',
    category: 'games',
    condition: { type: 'game_perfect', gameType: 'kanji-draw' },
    xpReward: 200,
    rarity: 'rare',
  },
  {
    key: 'wordsmith_game',
    name: 'Sentence Master',
    description: 'Perfect score in sentence builder',
    icon: '/images/badges/wordsmith_game.svg',
    category: 'games',
    condition: { type: 'game_perfect', gameType: 'sentence-builder' },
    xpReward: 200,
    rarity: 'rare',
  },
  {
    key: 'all_games',
    name: 'Jack of All Games',
    description: 'Play all 6 game types',
    icon: '/images/badges/all_games.svg',
    category: 'games',
    condition: { type: 'games_played', count: 6 },
    xpReward: 200,
    rarity: 'uncommon',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPECIAL (8)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: 'night_owl',
    name: 'Night Owl',
    description: 'Study after midnight',
    icon: '/images/badges/night_owl.svg',
    category: 'special',
    condition: { type: 'reviews_completed', count: 1 },
    xpReward: 50,
    rarity: 'common',
  },
  {
    key: 'early_bird',
    name: 'Early Bird',
    description: 'Study before 6 AM',
    icon: '/images/badges/early_bird.svg',
    category: 'special',
    condition: { type: 'reviews_completed', count: 1 },
    xpReward: 50,
    rarity: 'common',
  },
  {
    key: 'weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Study on both Saturday and Sunday',
    icon: '/images/badges/weekend_warrior.svg',
    category: 'special',
    condition: { type: 'streak_days', count: 2 },
    xpReward: 50,
    rarity: 'common',
  },
  {
    key: 'first_share',
    name: 'Social Butterfly',
    description: 'Share your profile',
    icon: '/images/badges/first_share.svg',
    category: 'social',
    condition: { type: 'reviews_completed', count: 0 },
    xpReward: 50,
    rarity: 'common',
  },
  {
    key: 'comeback',
    name: 'The Comeback',
    description: 'Return after 7+ days away',
    icon: '/images/badges/comeback.svg',
    category: 'special',
    condition: { type: 'streak_days', count: 1 },
    xpReward: 100,
    rarity: 'uncommon',
  },
  {
    key: 'marathon',
    name: 'Study Marathon',
    description: 'Study for 60+ minutes in one session',
    icon: '/images/badges/marathon.svg',
    category: 'special',
    condition: { type: 'reviews_completed', count: 1 },
    xpReward: 300,
    rarity: 'rare',
  },
  {
    key: 'listening_ace',
    name: 'Listening Ace',
    description: 'Perfect score in listening game',
    icon: '/images/badges/listening_ace.svg',
    category: 'games',
    condition: { type: 'game_perfect', gameType: 'listening' },
    xpReward: 200,
    rarity: 'rare',
  },
  {
    key: 'typing_pro',
    name: 'Typing Pro',
    description: 'Perfect score in typing game',
    icon: '/images/badges/typing_pro.svg',
    category: 'games',
    condition: { type: 'game_perfect', gameType: 'typing' },
    xpReward: 200,
    rarity: 'rare',
  },
];

/**
 * Lookup map keyed by achievement key for O(1) retrieval.
 */
export const ACHIEVEMENTS_MAP: Record<string, AchievementDefinition> =
  Object.fromEntries(ACHIEVEMENTS.map((a) => [a.key, a]));
